[package]
name = "sandlock-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
description = "C ABI for sandlock process sandbox"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = ["http"]
http = ["sandlock-core/http"]

[dependencies]
libc = "0.2"
sandlock-core = { version = "0.8.9", path = "../sandlock-core", default-features = false }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
tempfile = "3"
ring = "0.17"
tar = "0.4"

